### ISSUE TITLE
renovate-bot failed to propose google-cloud-shared-dependencies update in googleapis repo

### ISSUE THREAD

**Issue by stephaniewang526** [renovatebot/app-support#118]
We had to make below manual update ourselves since renovate-bot did not propose these updates:

https://github.com/googleapis/java-bigqueryconnection/pull/358

Similar happened in https://github.com/googleapis/java-firestore.

We did get renovate-bot updates in our many other 70+ Google-provided repos. Not sure why this one was missed.

Could you investigate and let us know why the bot did not work?

Thank you!

**Comment by Neenu1995** [comment]
Renovate-bot did not propose the same changes in following repo as well:
[googleapis/java-speech](https://github.com/googleapis/java-speech/pull/480)

**Comment by rarkins** [comment]
Hi, I have identified the root cause:
- At one or more times recently, GitHub had a glitch where it returned a 500 error when we ask it to fork repos
- We incorrectly classified that as a terminal failure and disabled each repo it happened to

Resolution:
- All googleapis/* repos have been unmarked from disabled state to be checked again immediately (done)
- Adjusting Renovate code so that it doesn't happen again: https://github.com/renovatebot/renovate/pull/9521

**Comment by stephaniewang526** [comment]
Great - thank you!
