### ISSUE TITLE
Renovate badge

### ISSUE THREAD

**Issue by tunnckoCore** [renovatebot/app-support#38]
Hey! :hand: 

I'm thinking to drop most of my badges and stick to as minimal as possible, but want to show that my deps are always up to date, because Semantic-Release (probably) and Renovate and good its specific config that i'm thinking now (low noises, big automation, plus pinning versions).

So i think this would be enough
[![Renovate - Always up to date][renovateapp-svg]][renovateapp-link]

[renovateapp-link]: https://renovateapp.com
[renovateapp-svg]: https://img.shields.io/badge/always-up_to_date-brightgreen.svg

```
[![Renovate - Always up to date][renovateapp-svg]][renovateapp-link]

[renovateapp-link]: https://renovateapp.com
[renovateapp-svg]: https://img.shields.io/badge/always-up_to_date-brightgreen.svg
```

**Comment by rarkins** [comment]
Renovate would suggest the badge in a PR once per repo - after onboarding - and anyone with multiple repos using their own preset could even disable that behaviour because they will merge the custom preset as part of onboarding.

If you want to remove a badge after adding it, you'd remove it yourself - no PR from Renovate for that. The `badgeUrl` option controls only whether it is *suggested* or not.

I would be pretty certain if you made badge addition DIY-only, you'd get something like 3% adding it to their README. If you proposed it in a PR, I would expect it to be 10x that or more, especially if the badge content is *meaningful* (e.g. providing context on the dependency state of the repo). The difference between those two values is simply down to it being convenient or not. Ignoring the fact that I made those figures up, it's up to you which is more important: the 27% of users who want it but can't be bothered adding it manually, or the 70% who'd close the PR.

Remembering that Renovate already raises 100s/1000s for PRs per-repo in most cases, I'd hope it's a rare for someone to object to 1 additional PR immediately after onboarding which suggests a badge that shows visitors to the repo (a) that you keep dependencies update, and (b) how well you're keeping up with that. I've seen other services *include* the badge readme update with their *onboarding*, i.e. if you don't want it then you have to manually delete the readme.md change out of the initial PR before you can merge it. What I'm proposing is much politer.

We would also not want unsigned image URLs for private repos, so providing instructions on how/where to get the full URL would make it even less likely that people add it manually. 

What I can maybe do though is make a random selection of users accounts initially (for example, just users starting with `n`) see what the ratio is of merged:open:closed. I could also delay that introduction until the badge can nicely say how many updates there are and colour code a "score", so people are more likely to see the value.

**Comment by rarkins** [comment]
Nothing really planned yet. Moving this to the app repo though because it's dependent on the service and not the open source code.

**Comment by mizozobu** [comment]
If you just need a shortcut to your dashboard like me, here it is.
Customize it to your preference on https://shields.io

[![renovate](https://img.shields.io/badge/renovate-enabled-%231A1F6C?logo=renovatebot)](https://app.renovatebot.com/dashboard)
[![renovate](https://img.shields.io/badge/renovate-configured-green?logo=renovatebot)](https://app.renovatebot.com/dashboard)
[![renovate](https://img.shields.io/badge/maintaied%20with-renovate-blue?logo=renovatebot)](https://app.renovatebot.com/dashboard)
