### ISSUE TITLE
Passing status checks not detected immediately by app

### ISSUE THREAD

**Issue by felixfbecker** [renovatebot/app-support#39]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
There was a new version of one of our packages released: https://github.com/sourcegraph/sourcegraph-extension-api/releases/tag/v18.0.2

![image](https://user-images.githubusercontent.com/10532611/47583397-2f3a8780-d90c-11e8-8ee6-2783c9131668.png)

Renovate did a run on a depending repo:

![image](https://user-images.githubusercontent.com/10532611/47583734-2e562580-d90d-11e8-8ee2-d2b52a77a6d1.png)

and recognized the new version. It created a branch for the update:

![image](https://user-images.githubusercontent.com/10532611/47583772-4332b900-d90d-11e8-9fe9-3a70bbfc7c77.png)

for which CI passed 10min later:

![image](https://user-images.githubusercontent.com/10532611/47583810-60678780-d90d-11e8-8e3c-ee0fb969c4f0.png)

Now it's been roughly half an hour since then and I would expect to see a PR created (or automerging be performed if confgigured), but nothing is happening. Renovate has not done another run so far.

It's very important that when a change is merged into one repo, we can be confident that it's going to be updated in other repos "as soon as possible". Ideally it should only be bound to the CI time. I would expect no significant delays (of upward to an hour like seen here) between the steps in this workflow. I've heard confusion from coworkers about why these updates are not progressing / seemingly getting stuck and people eventually do updates manually because they don't trust the system.

Is this expected, or a bug? If it's expected, is there a way this could be improved? Could Renovate maybe listen to commit status webhooks to trigger a run that creates the PR/automerges as soon as CI passes?

**Comment by rarkins** [comment]
Are there any repos you can point me to so that I can check the historical webhooks received?

**Comment by rarkins** [comment]
FYI I added this `app-support` repo to separate out app-specific topics from the Renovate CLI repo, so just moved this issue accordingly.

Renovate too has a "what's the combined status of this branch?" logic but I never ported it to the webhook handling. I still find it pretty frustrating that GitHub makes it so hard to simply know "is this branch green?". 

@travi thanks for the background info. There's necessarily still going to be *some* delay when things are event-driven instead of in the same pipeline. i.e. GitHub sends webhooks any time any status check events happens, then Renovate's webhook handler has to (unfortunately) query multiple endpoints to derive a combined status, then a job is queued up, Renovate runs, and then *should* merge that branch during that run (assuming no conflicts, it's still up-to-date, etc). This would hopefully be bound to around a minute or so in most cases.

FYI the key blocker for this in the past was the need to either:
- Trigger a run by Renovate for *every* branch that turns green or red, "just in case", or
- Need to store state about every branch's automerge setting for every repo, and Renovate doesn't currently do that

I'm leaning towards the latter, naturally.

**Comment by travi** [comment]
> I still find it pretty frustrating that GitHub makes it so hard to simply know "is this branch green?".

1000x yes, this!

> There's necessarily still going to be some delay when things are event-driven instead of in the same pipeline.

Totally understood. the natural delay that results from the complexities of tying a complex pipeline like this together are pretty clear to me and accepted, assuming things are still moving along. waiting for queues makes sense, but not being queued at all yet is significantly more painful for this type of use case.

> This would hopefully be bound to around a minute or so in most cases.

I think that is pretty acceptable. I'll admit that I'm used to faster since greenkeeper-keeper ran as its own instance and traffic was low enough to avoid queues since it was self-hosted. However, minutes are totally reasonable. The current behavior is simply significantly more than that.

> I'm leaning towards the latter, naturally.

Seems reasonable to me. I'm more than happy to discuss anything about my process in more detail where it would be helpful, but I imagine you have your head pretty well around what is left.

The main question on my mind is timing since it does sound like this could still be a fair amount of work. Is it reasonable to think that immediate queuing of the renovate run based on status success could be completed by the planned June shutdown of Greenkeeper? Not trying to add more pressure, but that date is a pretty important one as I evaluate what my options are.

> FYI I added this app-support repo to separate out app-specific topics from the Renovate CLI repo, so just moved this issue accordingly.

noted. i'll keep that in mind in the future. thanks!

**Comment by rarkins** [comment]
This has now been implemented on the backend. It's quite challenging:
- It's not just status checks, it's also check runs, which are separate endpoints to query
- When GitHub sends a webhook that something has passed, it doesn't tell us whether there are other status checks will pending or not

Querying the API after *any* passing webhook notification would be too aggressive, so we implemented this with a 5 minute "debounce" - Renovate's backend will query the SHA's combined status 5 minutes after the last successful webhook was received. If the combined result is green, and the branch is configured for automerge, then a job will be enqueued immediately.

i.e. you should hopefully see automerging happening ~6 minutes after branches go green. We will evaluate whether a shorter debounce period can be used in future, but for now this is a big improvement over the ~30 minute average wait time before.

**Comment by travi** [comment]
Super excited for this. Thanks a ton!

**Comment by travi** [comment]
i've already had a chance to see this in action on a bunch of new PRs and it seems to be working great. a very welcome improvement. thanks again!

**Comment by rarkins** [comment]
Unfortunately I've needed to roll back this feature due some undesirable database spiking caused by locks. I'll comment back here again once it's re-enabled.

**Comment by rarkins** [comment]
I'm going to archive this repository so that we have conversations in one place. Therefore please create an "App Support" discussion here if this problem or suggestion is still relevant: https://github.com/renovatebot/renovate/discussions
