### ISSUE TITLE
Gustavo Saiani feedback

### ISSUE THREAD

**Issue by gusaiani** [renovatebot/app-support#73]
Hey fellows, please reconsider your growth strategy.

It's not cool to have bot PRs trying to install your product all over the place.

If that happens again in one of the repos I maintain, I will report you.

Thank you.

**Comment by gusaiani** [comment]
@rarkins, I had not taken a look at Renovate's page.

If it helps to illustrate our case, our teammate who installed Renovate did not grasp from the instructions that the tool would **instantaneously** add PRs to nearly **all** our company's repos.

According to him, he had installed this in the past in other orgs and at the time it wasn't automated so he had control over which repos got it.

So he never thought to give anyone a heads-up of the impending PRs. And as no one saw them coming, the emotional reaction to it was of rejection across the board.

Maybe it would help the cause to have an even clearer warning stating that, upon instalation, all or nearly all of your company's repos would get bot PRs right away.

Or giving the option to open PRs per repo at the team's discretion.

Hope this adds something. Cheers!

**Comment by rarkins** [comment]
> If it helps to illustrate our case, our teammate who installed Renovate did not grasp from the instructions that the tool would **instantaneously** add PRs to nearly **all** our company's repos.

He literally picked "All repositories". The tool's job is to raise PRs, and it clearly says you can expect an onboarding PR.

> According to him, he had installed this in the past in other orgs and at the time it wasn't automated so he had control over which repos got it.

He's mistaken, the tool's onboarding process for both GitHub and Renovate hasn't changed in years since the app interface was launched. The control over which repos are enabled is at installation time, with the "Select repositories" option I showed in the screenshot earlier. He picked "All repositories".

> So he never thought to give anyone a heads-up of the impending PRs. And as no one saw them coming, the emotional reaction to it was of rejection across the board.

OK, no problem. I've put a manual rule for the account so no future PRs are raised.

**Comment by gusaiani** [comment]
Understood, thank you 👍
