### ISSUE TITLE
A way to boost auto-merge job frequency

### ISSUE THREAD

**Issue by jraoult** [renovatebot/app-support#90]
👋 We are trying Renovate on our private repository. I enabled auto-merge and set the option "prConcurrentLimit": 2 to limit stale rebasing every time something is merged. It seems both auto-merge and the PR jobs are running once per hour, which doesn't allow for the updates queue to drain.

Is there a way to get Renovate to run a new cycle as soon as a PR is merged or at least at a higher fixed pace (may be 4 times an hour)? May be with a paying option?

**Comment by rarkins** [comment]
> Is there a way to get Renovate to run a new cycle as soon as a PR is merged

Unless a job is already running, or a job somehow got stuck within the last hour, you should always see Renovate running immediately after any merge of its PRs (whether automerge or manual merge). And even if a job was already in the in-progress queue, another job should be queued up behind it to run when either the current job finishes or times out after an hour.

Earlier this month I enabled some webhook listening/queueing for passing status checks for this reason (see #39) but unfortunately it resulted in some nasty Database lockups so it will need to wait a little while until we look into a different queuing system.

The best I can suggest is to enable `dependencyDashboard` because it has a checkbox at the bottom that can request a run of Renovate (i.e. without having to request a *rebase*, which would only defect the automerging until another run). If you tick that checkbox then Renovate should start on the repo within seconds.

If you *manually* merge a Renovate PR that should also trigger a run too, e.g. you are doing the merge manually but at least Renovate should run right away and rebase any conflicted ones and create any new ones if there's any concurrent limit left.

If this can be regarded as a duplicate of #39 (i.e. run soon after tests pass) then please close this issue.

If you are *not* seeing Renovate run immediately after a merge, then keep it open and we need more details because it should be happening already

**Comment by jraoult** [comment]
Hmm, thanks for your reply. I think indeed this is related to #39. I'll follow that thread instead.
